### PR TITLE
fix: Resolve frameSrc not found warning

### LINKED ISSUE #164: frameSrc was not found in __PLAYROOM_ALIAS__FRAME_COMPONENT__
After the latest upgrade there seems to appear some warnings. The app still works however.

image

---
node: v14.3.0
yarn: 1.22.4
playroom: 0.21.0
webpack: 4.43.0

### PR DESCRIPTION
**Pull request by mattcompiles**
Resolves #164

### CODE REVIEW

**Comment by maraisr** [comment]
Wait... I get it! So this "frameSrc" is something I can export from my frame component housed file? @mattcompiles

**Comment by mattcompiles** [comment]
That's correct.

**Comment by maraisr** [comment]
Do you think you can help me with a list of things that are undocumented with Playroom, so I can help you guys out in writing some. cc @mattcompiles @michaeltaranto @markdalgleish

**Comment by michaeltaranto** [comment]
This is currently a feature we are proving out, so it's deliberately undocumented at this point. We are hoping to get to building a site soon, but was there something else on your list?

**Comment by maraisr** [comment]
Generally speaking new features that are being tested get released under an @next tag, rather than the stable. Perhaps playroom could do something similar? 

And re the list, I was hoping you could provide one.

**Comment by michaeltaranto** [comment]
Worth remembering that Playroom is pre-1.0, so everything is a next tag.

We document the features that we are happy for users to start consuming. If consumers are digging into the code and using internal apis, that's fine as they are explicitly opting in to an unstable api.

**Comment by maraisr** [comment]
Oh right... Did not know that that 0.x.x means beta. My bad!

**Comment by maraisr** [comment]
Pretty funny hey.

**Comment by maraisr** [comment]
... I'm serious.

**Pull request merged**
