### PR TITLE
feat: Add a config panel with filters for preview frames

### PR DESCRIPTION
**Pull request by bradbarrow**
### Summary

Exposes a config panel that allows the user to select which themes or screen widths they want to see in the preview window.

### Motivation

Particularly when using both themes and multiple screen widths, the number of visible frames can be quite overwhelming both to navigate AND in terms of performance in the browser (10+ iframes reloading regularly).

### Opportunities

I think there's an opportunity to extend this feature to allow opting in to certain frames / themes via a query param 

e.g. `my.playroom.com/?code=base64String&themes=seekAnz&widths=320,768`

### Preview

image

### CODE REVIEW

**Comment by bradbarrow** [comment]
Anything I can do to help move this forward folks? What do we think of the proposed changes?

**Comment by michaeltaranto** [comment]
Sorry to leave you hanging. We are actively working on a bit of an overhaul of playroom at the moment. In this refactor we are hoping to provide a better mechanism for both local stored and url addressable settings. As part of that we will be incorporating some of your ideas, as configurable themes/widths is a big priority for us internally too.

**Comment by michaeltaranto** [comment]
FYI just opened this [PR](https://github.com/seek-oss/playroom/pull/107). Can you pull it down and give it a run with your use case. If that works as expected we can close this PR. Let me know if you have any feedback.

**Comment by michaeltaranto** [comment]
Closing based on the `v0.13.1` release. Thanks for your inspiration 👏

**Pull request closed without merging**
